version: "3"
services:
  go-example-main:
    image: golang:1.13.3-buster
    volumes: 
      - ./:/go/src/go-example
    working_dir: /go/src/go-example
    command: go run main.go
    links:
      - go-example-mysql
    environment:
      MYSQL_HOST: go-example-mysql
      MYSQL_PORT: 3306   
      MYSQL_PASSWORD: go-example-mysql

  go-example-mysql:
    image: mysql:5.7.28
    environment: 
      MYSQL_ROOT_PASSWORD: go-example-mysql
    volumes: 
      - ./local/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"