// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: app/interface/grpc/package/pause.proto

package pause

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Pause service

type PauseService interface {
	Create(ctx context.Context, in *PauseRequest, opts ...client.CallOption) (*PauseResponse, error)
}

type pauseService struct {
	c    client.Client
	name string
}

func NewPauseService(name string, c client.Client) PauseService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pause"
	}
	return &pauseService{
		c:    c,
		name: name,
	}
}

func (c *pauseService) Create(ctx context.Context, in *PauseRequest, opts ...client.CallOption) (*PauseResponse, error) {
	req := c.c.NewRequest(c.name, "Pause.Create", in)
	out := new(PauseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pause service

type PauseHandler interface {
	Create(context.Context, *PauseRequest, *PauseResponse) error
}

func RegisterPauseHandler(s server.Server, hdlr PauseHandler, opts ...server.HandlerOption) error {
	type pause interface {
		Create(ctx context.Context, in *PauseRequest, out *PauseResponse) error
	}
	type Pause struct {
		pause
	}
	h := &pauseHandler{hdlr}
	return s.Handle(s.NewHandler(&Pause{h}, opts...))
}

type pauseHandler struct {
	PauseHandler
}

func (h *pauseHandler) Create(ctx context.Context, in *PauseRequest, out *PauseResponse) error {
	return h.PauseHandler.Create(ctx, in, out)
}
