// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/interface/grpc/package/pause.proto

package pause

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PauseType int32

const (
	PauseType_STANDARD    PauseType = 0
	PauseType_EXCEPTIONAL PauseType = 1
)

var PauseType_name = map[int32]string{
	0: "STANDARD",
	1: "EXCEPTIONAL",
}

var PauseType_value = map[string]int32{
	"STANDARD":    0,
	"EXCEPTIONAL": 1,
}

func (x PauseType) String() string {
	return proto.EnumName(PauseType_name, int32(x))
}

func (PauseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_20995f9011655d84, []int{0}
}

type PauseRequest struct {
	StartDate            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Type                 PauseType            `protobuf:"varint,3,opt,name=type,proto3,enum=PauseType" json:"type,omitempty"`
	ValueProductId       string               `protobuf:"bytes,4,opt,name=value_product_id,json=valueProductId,proto3" json:"value_product_id,omitempty"`
	AccountId            string               `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PauseRequest) Reset()         { *m = PauseRequest{} }
func (m *PauseRequest) String() string { return proto.CompactTextString(m) }
func (*PauseRequest) ProtoMessage()    {}
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20995f9011655d84, []int{0}
}

func (m *PauseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseRequest.Unmarshal(m, b)
}
func (m *PauseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseRequest.Marshal(b, m, deterministic)
}
func (m *PauseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseRequest.Merge(m, src)
}
func (m *PauseRequest) XXX_Size() int {
	return xxx_messageInfo_PauseRequest.Size(m)
}
func (m *PauseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PauseRequest proto.InternalMessageInfo

func (m *PauseRequest) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *PauseRequest) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *PauseRequest) GetType() PauseType {
	if m != nil {
		return m.Type
	}
	return PauseType_STANDARD
}

func (m *PauseRequest) GetValueProductId() string {
	if m != nil {
		return m.ValueProductId
	}
	return ""
}

func (m *PauseRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type PauseResponse struct {
	ResposneInfo         string   `protobuf:"bytes,1,opt,name=resposne_info,json=resposneInfo,proto3" json:"resposne_info,omitempty"`
	PauseId              string   `protobuf:"bytes,2,opt,name=pause_id,json=pauseId,proto3" json:"pause_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseResponse) Reset()         { *m = PauseResponse{} }
func (m *PauseResponse) String() string { return proto.CompactTextString(m) }
func (*PauseResponse) ProtoMessage()    {}
func (*PauseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20995f9011655d84, []int{1}
}

func (m *PauseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseResponse.Unmarshal(m, b)
}
func (m *PauseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseResponse.Marshal(b, m, deterministic)
}
func (m *PauseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseResponse.Merge(m, src)
}
func (m *PauseResponse) XXX_Size() int {
	return xxx_messageInfo_PauseResponse.Size(m)
}
func (m *PauseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PauseResponse proto.InternalMessageInfo

func (m *PauseResponse) GetResposneInfo() string {
	if m != nil {
		return m.ResposneInfo
	}
	return ""
}

func (m *PauseResponse) GetPauseId() string {
	if m != nil {
		return m.PauseId
	}
	return ""
}

func init() {
	proto.RegisterEnum("PauseType", PauseType_name, PauseType_value)
	proto.RegisterType((*PauseRequest)(nil), "PauseRequest")
	proto.RegisterType((*PauseResponse)(nil), "PauseResponse")
}

func init() {
	proto.RegisterFile("app/interface/grpc/package/pause.proto", fileDescriptor_20995f9011655d84)
}

var fileDescriptor_20995f9011655d84 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x50, 0x4b, 0xcf, 0xd3, 0x30,
	0x10, 0xfc, 0x52, 0xfa, 0xca, 0xf6, 0x41, 0xe5, 0x53, 0xa9, 0x04, 0xaa, 0x8a, 0x84, 0x42, 0x0f,
	0xb1, 0x14, 0xc4, 0x01, 0x71, 0xaa, 0xda, 0x1e, 0x22, 0xa1, 0xb6, 0x0a, 0x39, 0x70, 0x8b, 0x9c,
	0x78, 0x13, 0x22, 0x5a, 0xdb, 0xc4, 0x36, 0x52, 0x7f, 0x32, 0xff, 0x02, 0xc5, 0x6d, 0x79, 0x9c,
	0xb8, 0xad, 0x67, 0x67, 0xd6, 0x33, 0x03, 0x6f, 0x98, 0x52, 0xb4, 0x16, 0x06, 0x9b, 0x92, 0x15,
	0x48, 0xab, 0x46, 0x15, 0x54, 0xb1, 0xe2, 0x1b, 0xab, 0x90, 0x2a, 0x66, 0x35, 0x86, 0xaa, 0x91,
	0x46, 0x2e, 0x3e, 0x56, 0xb5, 0xf9, 0x6a, 0xf3, 0xb0, 0x90, 0x17, 0x5a, 0xc9, 0x33, 0x13, 0x15,
	0x75, 0x8b, 0xdc, 0x96, 0x54, 0x99, 0xab, 0x42, 0x4d, 0x4d, 0x7d, 0x41, 0x6d, 0xd8, 0x45, 0xfd,
	0x99, 0x6e, 0xe2, 0xd5, 0x4f, 0x0f, 0xc6, 0xa7, 0xf6, 0x58, 0x82, 0xdf, 0x2d, 0x6a, 0x43, 0x3e,
	0x00, 0x68, 0xc3, 0x1a, 0x93, 0x71, 0x66, 0x70, 0xee, 0x2d, 0xbd, 0x60, 0x14, 0x2d, 0xc2, 0x4a,
	0xca, 0xea, 0x7c, 0xff, 0x30, 0xb7, 0x65, 0x98, 0x3e, 0xce, 0x24, 0xbe, 0x63, 0xef, 0x98, 0x41,
	0xf2, 0x1e, 0x86, 0x28, 0xf8, 0x4d, 0xd8, 0xf9, 0xaf, 0x70, 0x80, 0x82, 0x3b, 0xd9, 0x2b, 0xe8,
	0xb6, 0x2e, 0xe7, 0xcf, 0x96, 0x5e, 0x30, 0x8d, 0x20, 0x74, 0x76, 0xd2, 0xab, 0xc2, 0xc4, 0xe1,
	0x24, 0x80, 0xd9, 0x0f, 0x76, 0xb6, 0x98, 0xa9, 0x46, 0x72, 0x5b, 0x98, 0xac, 0xe6, 0xf3, 0xee,
	0xd2, 0x0b, 0xfc, 0x64, 0xea, 0xf0, 0xd3, 0x0d, 0x8e, 0x39, 0x79, 0x09, 0xc0, 0x8a, 0x42, 0x5a,
	0xe1, 0x38, 0x3d, 0xc7, 0xf1, 0xef, 0x48, 0xcc, 0x57, 0x47, 0x98, 0xdc, 0xa3, 0x6a, 0x25, 0x85,
	0x46, 0xf2, 0x1a, 0x26, 0x4d, 0x3b, 0x6b, 0x81, 0x59, 0x2d, 0x4a, 0xe9, 0xe2, 0xfa, 0xc9, 0xf8,
	0x01, 0xc6, 0xa2, 0x94, 0xe4, 0x05, 0x0c, 0x5d, 0xdb, 0xed, 0xc9, 0x8e, 0xdb, 0x0f, 0xdc, 0x3b,
	0xe6, 0xeb, 0x35, 0xf8, 0xbf, 0xcd, 0x92, 0x31, 0x0c, 0x3f, 0xa7, 0x9b, 0xc3, 0x6e, 0x93, 0xec,
	0x66, 0x4f, 0xe4, 0x39, 0x8c, 0xf6, 0x5f, 0xb6, 0xfb, 0x53, 0x1a, 0x1f, 0x0f, 0x9b, 0x4f, 0x33,
	0x2f, 0x8a, 0xa0, 0xe7, 0xb8, 0xe4, 0x2d, 0xf4, 0xb7, 0x0d, 0xb6, 0xc1, 0x27, 0xe1, 0xdf, 0xcd,
	0x2f, 0xa6, 0xe1, 0x3f, 0xee, 0x56, 0x4f, 0x79, 0xdf, 0xd5, 0xf6, 0xee, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x17, 0xc8, 0x82, 0x18, 0x0a, 0x02, 0x00, 0x00,
}
